### ISSUE TITLE
Seemingly Unfixable error

### ISSUE THREAD

**Issue by samsamsamsamlmao** [KinexDev/EasyInputs#1]
i get this error 
![image](https://user-images.githubusercontent.com/115862742/206356783-075b6cba-e044-4c80-a477-2b57c3423d9c.png)
this is my code
![image](https://user-images.githubusercontent.com/115862742/206356829-0e43c899-ac87-45dc-b11e-d8161f505505.png)
this is the error i get when i add a comma 
![image](https://user-images.githubusercontent.com/115862742/206356844-f4657682-0a3c-4e81-ac5d-83c7f6309e1f.png)

**Comment by KinexDev** [comment]
Sorry for the long time it took for me to reply 😊 I think i explained it wrong in the documentation. The EasyHand is a enum, and inside of that enum you have LeftHand and RightHand. So you have to pick which hand you want to use. Here are some examples on how to use it
![RightHand](https://user-images.githubusercontent.com/104727812/206534907-c3d7eb3f-4f4f-4e9b-97c6-c3c840188f67.png)
![LeftHand](https://user-images.githubusercontent.com/104727812/206534910-96358b1d-f2f2-4c29-b9e4-c60cc7fba729.png)
You can also do a value that you can edit in the unity editor
![Value](https://user-images.githubusercontent.com/104727812/206534902-9097e8a1-393e-4bf7-8f05-3331a9b1e1aa.png)
![HandAnimations](https://user-images.githubusercontent.com/104727812/206535108-a717fc40-3e10-4eab-898e-1b8ced3dc913.png)

**Comment by samsamsamsamlmao** [comment]
thank you, this makes alot more sense now.

**Comment by Memerguygoogle** [comment]
fr
